name: Deploy GitHub Pages
on:
  workflow_run:
    workflows: ["Run Script"]
    types:
      - completed
permissions:
  pages: write
  id-token: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Build project
        run: |
          # Your build commands here
          # For example, `npm run build` or similar
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: . # Replace `./build` with the path to your built files
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4.0.5
        with:
          folder: . # Assuming `index.html` is in the root of the repo
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
